name: 'Run Bazel Command'
description: 'Runs bazel command with setup-bazel'
inputs:
  bazel-config:
    description: 'The bazel configuration to use.'
    required: false
    default: "--config=ci"
  bazel-command:
    description: 'The bazel command to run. Typically the arguments after bazelisk'
    required: true
  bazel-targets:
    description: 'The bazel targets'
    required: true
  cache-key:
    description: 'The cache key to uniquely identify this build'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "zulu"
        java-version: "17"
    - name: Setup Bazel
      uses: bazel-contrib/setup-bazel@0.8.5
      with:
        bazelisk-cache: true
        # Store build cache per workflow.
        disk-cache: ${{ inputs.cache-key }}-${{ github.workflow }}
        # Share repository cache between workflows.
        repository-cache: true

    - name: Run bazel command
      shell: bash
      run: bazelisk ${{ inputs.bazel-command }} ${{ inputs.bazel-config }} ${{ inputs.bazel-targets }}