name: CI workflow

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bazel build
        uses: ./.github/actions/bazel
        with:
          bazel-command: run
          bazel-targets: //:buildifier -- --mode=check -r $(pwd)
          cache-key: bazel-lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bazel build
        uses: ./.github/actions/bazel
        with:
          bazel-command: build
          bazel-targets: //...
          cache-key: bazel-build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Bazel test
        uses: ./.github/actions/bazel
        with:
          bazel-command: test
          bazel-targets: //...
          cache-key: bazel-test