name: Build workflow

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bazel build
        uses: ./.github/actions/bazel
        with:
          bazel-command: run //:buildifier -- --mode=check -r $(pwd)
          cache-key: bazel-lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bazel build
        uses: ./.github/actions/bazel
        with:
          bazel-command: build //...
          cache-key: bazel-build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Bazel test
        uses: ./.github/actions/bazel
        with:
          bazel-command: test //...
          cache-key: bazel-test